default: &default
  adapter: postgresql
  encoding: utf8
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] || ENV['DATABASE_PASSWORD'] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: spectre_development

test: &test
  adapter: sqlite3
  timeout: 5000
  database: db/test.sqlite3

cucumber:
  <<: *test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
