name: Test spectre

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: spectre
          POSTGRES_DB: spectre_test
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: trust
        ports: ["5432:5432"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        # uses: ruby/setup-ruby@v1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Set up test database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: spectre
        run: |
          bundle exec rake db:setup

      - name: Run tests
        run: bundle exec rake
